name: fwitter
description: A test task for Sibirix. Not Twitter. Fwitter.

publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  dio_smart_retry: ^1.2.0
  google_fonts: ^3.0.1
  riverpod: ^1.0.2
  flutter_riverpod: ^1.0.2
  auto_route: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.0.0
  card_loading: ^0.2.1
  font_awesome_flutter: ^10.1.0
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  hive_generator: ^1.1.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  color_dark: "#ffffff"
  image_dark: assets/images/splash.png